---
abstract: 'Produce formatted reports in PostScript'
author:
  - 'Christopher J. Madsen <perl@cjmweb.net>'
generated_by: 'Dist::Zilla version 1.092850'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PostScript-Report
requires:
  File::Spec: 0
  Font::AFM: 0
  List::Util: 0
  Moose: 0.65
  MooseX::AttributeHelpers: 0
  MooseX::AttributeTree: 0
  MooseX::Types: 0
  PostScript::File: 1.03
  String::RewritePrefix: 0
  namespace::autoclean: 0
resources:
  repository: http://github.com/madsen/postscript-report
version: 0.02
